// File generated by FlutterFire CLI & Firebase MCP Server config lookup.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS5qKqIHiaBywuI_z6cX6BxyBEG412MiY',
    appId: '1:159478560039:web:0e084a38ed114c9b39e502',
    messagingSenderId: '159478560039',
    projectId: 'tillnex-pos',
    authDomain: 'tillnex-pos.firebaseapp.com',
    storageBucket: 'tillnex-pos.firebasestorage.app',
    measurementId: 'G-YW1MRW68G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlahliurDm0Pi-N4TNu4CoxAmL5PhgXoE',
    appId: '1:159478560039:android:ee1e4b75a19b817239e502',
    messagingSenderId: '159478560039',
    projectId: 'tillnex-pos',
    storageBucket: 'tillnex-pos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBscxKQ1gPlsXpiGFqR0m2OeuVNQymtjc',
    appId: '1:159478560039:ios:bd5ec3de23fccf7339e502',
    messagingSenderId: '159478560039',
    projectId: 'tillnex-pos',
    storageBucket: 'tillnex-pos.firebasestorage.app',
    iosBundleId: 'com.tillnex.tillnexPos',
  );
}
